# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      GRADLE_OPTS: "-Dorg.gradle.internal.http.connectionTimeout=120000 -Dorg.gradle.internal.http.socketTimeout=120000"
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build fabric
        run: ./gradlew :fabric:build
      - name: build neoforge
        run: ./gradlew :neoforge:build
      - name: upload fabric artifact
        uses: actions/upload-artifact@v4
        with:
          name: fabric-artifacts
          path: |
            fabric/build/libs/*.jar
          if-no-files-found: error
      - name: upload neoforge artifact
        uses: actions/upload-artifact@v4
        with:
          name: neoforge-artifacts
          path: |
            neoforge/build/libs/*.jar
          if-no-files-found: error